const state={allCards:[],visibleCards:[],currentIndex:0,isFlipped:false,favorites:new Set(JSON.parse(localStorage.getItem("bcShinFavorites")||"[]"))};
const el={categorySelect:document.getElementById("categorySelect"),searchInput:document.getElementById("searchInput"),progressText:document.getElementById("progressText"),flashcard:document.getElementById("flashcard"),frontCategory:document.getElementById("frontCategory"),backCategory:document.getElementById("backCategory"),termText:document.getElementById("termText"),backTermText:document.getElementById("backTermText"),definitionText:document.getElementById("definitionText"),previousBtn:document.getElementById("previousBtn"),shuffleBtn:document.getElementById("shuffleBtn"),nextBtn:document.getElementById("nextBtn"),favoriteBtn:document.getElementById("favoriteBtn"),favoriteIcon:document.getElementById("favoriteIcon"),favoriteLabel:document.getElementById("favoriteLabel"),showAnswerBtn:document.getElementById("showAnswerBtn"),pronounceBtn:document.getElementById("pronounceBtn"),statusMessage:document.getElementById("statusMessage")};
function parseCSV(text){const rows=[];let row=[],field="",insideQuotes=false;for(let i=0;i<text.length;i++){const char=text[i],next=text[i+1];if(char==='"'&&insideQuotes&&next==='"'){field+='"';i++}else if(char==='"'){insideQuotes=!insideQuotes}else if(char===","&&!insideQuotes){row.push(field.trim());field=""}else if((char==="\n"||char==="\r")&&!insideQuotes){if(char==="\r"&&next==="\n")i++;row.push(field.trim());field="";if(row.some(cell=>cell!==""))rows.push(row);row=[]}else{field+=char}}if(field.length||row.length){row.push(field.trim());rows.push(row)}const[headers,...dataRows]=rows;return dataRows.map(values=>{const item={};headers.forEach((header,index)=>item[header]=values[index]||"");return item}).filter(card=>card.Term&&card.Definition)}
async function loadCards(){try{const response=await fetch("Insurance_Vocabulary.csv",{cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);state.allCards=parseCSV(await response.text());state.visibleCards=[...state.allCards];if(!state.allCards.length)throw new Error("No usable vocabulary cards.");populateCategories();renderCard()}catch(error){console.error(error);el.statusMessage.textContent="The vocabulary file could not be loaded. Open this project through a web server rather than by double-clicking index.html.";el.termText.textContent="Unable to load cards";el.definitionText.textContent="See the message below the flashcard."}}
function populateCategories(){[...new Set(state.allCards.map(card=>card.Category||"General"))].sort((a,b)=>a.localeCompare(b)).forEach(category=>{const option=document.createElement("option");option.value=category;option.textContent=category;el.categorySelect.appendChild(option)})}
function currentCard(){return state.visibleCards[state.currentIndex]}
function renderCard(){resetFlip();if(!state.visibleCards.length){el.termText.textContent="No matching cards";el.backTermText.textContent="No matching cards";el.definitionText.textContent="Try a different category or search term.";el.frontCategory.textContent="Search";el.backCategory.textContent="Search";el.progressText.textContent="Card 0 of 0";updateFavoriteButton(null);return}if(state.currentIndex>=state.visibleCards.length)state.currentIndex=0;const card=currentCard(),category=card.Category||"General";el.termText.textContent=card.Term;el.backTermText.textContent=card.Term;el.definitionText.textContent=card.Definition;el.frontCategory.textContent=category;el.backCategory.textContent=category;el.progressText.textContent=`Card ${state.currentIndex+1} of ${state.visibleCards.length}`;updateFavoriteButton(card)}
function flipCard(force){if(!state.visibleCards.length)return;state.isFlipped=typeof force==="boolean"?force:!state.isFlipped;el.flashcard.classList.toggle("is-flipped",state.isFlipped);el.showAnswerBtn.querySelector("span:last-child").textContent=state.isFlipped?"Show Term":"Show Answer"}
function resetFlip(){state.isFlipped=false;el.flashcard.classList.remove("is-flipped");el.showAnswerBtn.querySelector("span:last-child").textContent="Show Answer"}
function moveCard(direction){if(!state.visibleCards.length)return;state.currentIndex=(state.currentIndex+direction+state.visibleCards.length)%state.visibleCards.length;renderCard()}
function shuffleCards(){for(let i=state.visibleCards.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[state.visibleCards[i],state.visibleCards[j]]=[state.visibleCards[j],state.visibleCards[i]]}state.currentIndex=0;renderCard();showStatus("Cards shuffled.")}
function applyFilters(){const category=el.categorySelect.value,search=el.searchInput.value.trim().toLowerCase();state.visibleCards=state.allCards.filter(card=>{const categoryMatches=category==="All"||(card.Category||"General")===category;const searchMatches=!search||card.Term.toLowerCase().includes(search)||card.Definition.toLowerCase().includes(search);return categoryMatches&&searchMatches});state.currentIndex=0;renderCard()}
function toggleFavorite(){const card=currentCard();if(!card)return;if(state.favorites.has(card.Term))state.favorites.delete(card.Term);else state.favorites.add(card.Term);localStorage.setItem("bcShinFavorites",JSON.stringify([...state.favorites]));updateFavoriteButton(card)}
function updateFavoriteButton(card){const isFavorite=card?state.favorites.has(card.Term):false;el.favoriteBtn.setAttribute("aria-pressed",String(isFavorite));el.favoriteIcon.textContent=isFavorite?"★":"☆";el.favoriteLabel.textContent=isFavorite?"Favorited":"Favorite";el.favoriteBtn.disabled=!card}
function pronounceTerm(){const card=currentCard();if(!card)return;if(!("speechSynthesis" in window)){showStatus("Pronunciation is not supported by this browser.");return}window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(card.Term);utterance.lang="en-US";utterance.rate=.85;window.speechSynthesis.speak(utterance)}
function showStatus(message){el.statusMessage.textContent=message;clearTimeout(showStatus.timeout);showStatus.timeout=setTimeout(()=>el.statusMessage.textContent="",1800)}
el.flashcard.addEventListener("click",()=>flipCard());el.previousBtn.addEventListener("click",()=>moveCard(-1));el.nextBtn.addEventListener("click",()=>moveCard(1));el.shuffleBtn.addEventListener("click",shuffleCards);el.favoriteBtn.addEventListener("click",toggleFavorite);el.showAnswerBtn.addEventListener("click",()=>flipCard());el.pronounceBtn.addEventListener("click",pronounceTerm);el.categorySelect.addEventListener("change",applyFilters);el.searchInput.addEventListener("input",applyFilters);document.addEventListener("keydown",event=>{if(document.activeElement===el.searchInput)return;if(event.key==="ArrowLeft")moveCard(-1);if(event.key==="ArrowRight")moveCard(1);if(event.key===" "||event.key==="Enter"){event.preventDefault();flipCard()}});loadCards();
